### ISSUE TITLE
Intermittent timeout failure in Windows

### ISSUE THREAD

**Issue by sagenschneider** [officefloor/OfficeFloor#317]
[ERROR] Tests run: 4, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 39.46 s <<< FAILURE! - in net.officefloor.server.SocketManagerStressTest
[ERROR] testMultiClientThreaded(net.officefloor.server.SocketManagerStressTest)  Time elapsed: 22.074 s  <<< FAILURE!
junit.framework.AssertionFailedError: Socket timeout for 4396 : Read timed out
	at net.officefloor.server.SocketManagerStressTest.doPipeline(SocketManagerStressTest.java:165)
	at net.officefloor.server.SocketManagerStressTest.lambda$testMultiClientThreaded$2(SocketManagerStressTest.java:114)

**Comment by sagenschneider** [comment]
Potentially issue is that if close on socket does not clean up other sockets bound.

START: testCancelConnection (02:22:02)
SHUTDOWN: testCancelConnection (02:22:02), run time 0 seconds
May 20, 2019 2:22:02 AM net.officefloor.server.ssl.OfficeFloorDefaultSslContextSource createSslContext
WARNING: Using default OfficeFloor Key Store. This should only be used for testing and NEVER in production.
END: testCancelConnection (02:22:05), shutdown time 2 seconds
[ERROR] Tests run: 41, Failures: 0, Errors: 16, Skipped: 0, Time elapsed: 65.687 s <<< FAILURE! - in net.officefloor.server.http.OfficeFloorHttpServerImplementationTest
[ERROR] testSingleSecureFileRequest(net.officefloor.server.http.OfficeFloorHttpServerImplementationTest)  Time elapsed: 2.327 s  <<< ERROR!
java.nio.channels.ClosedSelectorException

**Comment by sagenschneider** [comment]
Improved engine to avoid long running processing.  Not had issue for past few months in nightly builds.
